from keras.datasets import fashion_mnist
(trainX, trainy), (testX, testy) = fashion_mnist.load_data()
validateX = trainX[54000:]
validateY = trainy[54000:]
trainX = trainX[:54000]
trainy = trainy[:54000]

pip install keras


In [73]:
## load training data and test data

import pandas as pd
import numpy as np
data_train = pd.read_csv("fashion-mnist_train.csv")
data1 = data_train
trainx = data1.drop(["label"],axis=1).to_numpy()
trainy = data1["label"].to_numpy()
data_test = pd.read_csv("fashion-mnist_test.csv")
data2 = data_test
testx = data2.drop(["label"],axis=1).to_numpy()
testy = data2["label"].to_numpy()

In [74]:
## split training data into train and validation data

validateX = trainx[54000:]
validateY = trainy[54000:]
trainX = trainx[:54000]
trainY = trainy[:54000]


print('Train: X = ', trainX.shape)
print('Train: Y = ', trainY.shape)
print('Test: X = ', testx.shape)
print('Test: Y = ', testy.shape)
print('Validate: X = ', validateX.shape)
print('Validate: Y = ', validateY.shape)

Train: X =  (54000, 784)
Train: Y =  (54000,)
Test: X =  (10000, 784)
Test: Y =  (10000,)
Validate: X =  (6000, 784)
Validate: Y =  (6000,)


'''0 T-shirt/top
1 Trouser
2 Pullover
3 Dress
4 Coat
5 Sandal
6 Shirt
7 Sneaker
8 Bag
9 Ankle boot'''




import matplotlib.pyplot as plt

cnt = 0
label_display_name = ["T-shirt/top", "Trouser", "Pullover", "Dress", "Coat", "Sandal", "Shirt", "Sneaker", "Bag", "Ankle boot"]
label = []

for i in range(1, trainX.shape[0]):

    if trainY[i] not in label:
        cnt = cnt + 1
        label.append(trainY[i])
        plt.subplot(2, 5, cnt)
        # Insert ith image with the color map 'grap'
        plt.imshow(trainX[i], cmap=plt.get_cmap('gray'))
        plt.title(label_display_name[trainY[i]])

    if cnt == 10:
        break

# Display the entire plot
plt.show()

In [75]:
## One hot encoding for output


trainyy = [np.zeros(10, dtype=int) for i in range(trainX.shape[0])]
testyy = [np.zeros(10, dtype=int) for i in range(testx.shape[0])]
for i in range(trainX.shape[0]):
    trainyy[i][trainY[i]-1] = 1

for i in range(testx.shape[0]):
    testyy[i][testy[i]-1] = 1
trainyy = np.array(trainyy)
testyy = np.array(testyy)
print(trainyy[0])
print(testyy[0])

[0 1 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 1]


In [81]:
print(trainX.shape)

(54000, 784)


In [84]:
from gradient_descent_FFNN import gradient_descent
from training import train_model
# from utility import random_initialize
from activation_functions import sigmoid_vector
Weights, Biases = train_model(trainX, trainyy, epochs=3, num_of_hidden_layers=3, size_of_layers=32, learning_rate=0.1, optimizer="sgd", batch_size=1, weight_init_type=random_initialize, activation_function=sigmoid_vector)

TypeError: 'NoneType' object is not subscriptable

In [64]:
def random_initialize(number_of_layers, nodes_per_hidden_layer, nodes_in_output_layer):
    W = np.random.rand(number_of_layers-1, nodes_per_hidden_layer ,nodes_per_hidden_layer)
    B = np.random.rand(number_of_layers-1, nodes_per_hidden_layer)
    WL = np.random.rand(nodes_per_hidden_layer,nodes_in_output_layer)
    BL = np.random.rand(nodes_in_output_layer)
    # W_list = list(W).append(WL)
    # B_list = list(B).append(BL)
    W_list = W.tolist() + [(WL.tolist())]
    B_list = B.tolist() + [(BL.tolist())]
    return W, B

In [66]:
# from utility import random_initialize
Weights, Biases = random_initialize(2,2,3)

In [67]:
print(Weights)

[[[0.81681037 0.34851979]
  [0.92166803 0.18457711]]]


In [28]:
data_test = pd.read_csv("fashion-mnist_test.csv")
data2 = data_test
testx = data2.drop(["label"],axis=1).to_numpy()
testy = data2["label"].to_numpy()

In [9]:
data = pd.read_csv("fashion-mnist_train.csv")

In [10]:
data.head()

label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0      2       0       0       0       0       0       0       0       0   
1      9       0       0       0       0       0       0       0       0   
2      6       0       0       0       0       0       0       0       5   
3      0       0       0       0       1       2       0       0       0   
4      3       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0        30        43         0   
3       0  ...         3         0         0         0         0         1   
4       0  ...         0         0         0         0         0         0   

   pixel781  pixel782  pixel783  pixel784  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [14]:
data1 = data

In [17]:
data1.drop(["label"],axis=1)

pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
0           0       0       0       0       0       0       0       0       0   
1           0       0       0       0       0       0       0       0       0   
2           0       0       0       0       0       0       0       5       0   
3           0       0       0       1       2       0       0       0       0   
4           0       0       0       0       0       0       0       0       0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
59995       0       0       0       0       0       0       0       0       0   
59996       0       0       0       0       0       0       0       0       0   
59997       0       0       0       0       0       0       0       0       0   
59998       0       0       0       0       0       0       0       0       0   
59999       0       0       0       0       0       0       0       0       0   

       pixel10  ...  pixel775  pixel776  pixel777  pixel778  pixel779  \
0            0  ...         0         0         0         0         0   
1            0  ...         0         0         0         0         0   
2            0  ...         0         0         0        30        43   
3            0  ...         3         0         0         0         0   
4            0  ...         0         0         0         0         0   
...        ...  ...       ...       ...       ...       ...       ...   
59995        0  ...         0         0         0         0         0   
59996        0  ...        73         0         0         0         0   
59997        0  ...       160       162       163       135        94   
59998        0  ...         0         0         0         0         0   
59999        0  ...         0         0         0         0         0   

       pixel780  pixel781  pixel782  pixel783  pixel784  
0             0         0         0         0         0  
1             0         0         0         0         0  
2             0         0         0         0         0  
3             1         0         0         0         0  
4             0         0         0         0         0  
...         ...       ...       ...       ...       ...  
59995         0         0         0         0         0  
59996         0         0         0         0         0  
59997         0         0         0         0         0  
59998         0         0         0         0         0  
59999         0         0         0         0         0  

[60000 rows x 784 columns]

In [20]:
import numpy as np
trainx = data1.drop(["label"],axis=1).to_numpy()
trainy = data1["label"].to_numpy()
trainx.shape

(60000, 784)

In [21]:
trainx[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   4,   0,   0,
         0,   0,   0,  62,  61,  21,  29,  23,  51, 136,  61,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,  88, 201, 228, 225, 255, 115,  62, 137, 255, 235, 222,
       255, 135,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,  47, 252, 234, 238, 224, 215, 215, 229, 108, 180, 207,
       214, 224, 231, 249, 254,  45,   0,   0,   0,   0,   0,   0,   0,
         0,   1,   0,   0, 214, 222, 210, 213, 224, 225, 217, 22

In [22]:
trainy = data1["label"].to_numpy()

In [24]:
trainy.shape

(60000,)